# customer-management-systemwith-excceptionhandling
in testor we have centralized exception handling 
i created validate class which throws the exception if found true and using throws keyword it is handled by it's caller i.e in testor 
for that we have created try and catch block in testor 
to give the message at the time of exception we used invalidinputexception class where we pass the message 
